export enum AdminNotificationEvent {
  NEW_CLIENT = 'NEW_CLIENT',
  NEW_APPOINTMENT = 'NEW_APPOINTMENT',
  APPOINTMENT_CANCELLED = 'APPOINTMENT_CANCELLED',
  APPOINTMENT_RESCHEDULED = 'APPOINTMENT_RESCHEDULED',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  PAYMENT_CANCELLED = 'PAYMENT_CANCELLED',
  ACCOUNT_DELETED = 'ACCOUNT_DELETED',
}
